import Navbar from "@/components/Navbar";
import "../node_modules/bootstrap/dist/css/bootstrap.min.css";

export const metadata = {
  title: "Crud Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <div>{children}</div>
      </body>
    </html>
  );
}
